name: auto_routing_eg
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  auto_route_generator: ^5.0.3
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
